### ISSUE TITLE
SSH handshake failure

### ISSUE THREAD

**Issue by onderogluserdar** [geerlingguy/packer-centos-6#13]
Hello. I'm getting ssh handshake failure error when using packer.

packer -v
0.12.2

Virtualbox
5.1.14r112924

==> virtualbox-iso: Starting HTTP server on port 8506
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2794)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-centos-6.8-x86_64 --memory 512
    virtualbox-iso: Executing: modifyvm packer-centos-6.8-x86_64 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5995
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

I didn't see the problem when packing centos7.

**Comment by mlcooper** [comment]
@onderogluserdar I see that you closed this issue, but what was the fix?  I am running into the same issue now with packer 0.12.2 and virtualbox 5.1.16.  Thanks!

**Comment by mmapixio** [comment]
It's unfortunate this was closed as I can rather reliably reproduce it, even on 1.0.0 and CentOS7 with virtualbox-iso.  The downside is that if I just 'reexecute' the build step, it will succeed... or sometimes fail.  Would be great to find a way of debugging what's actually happening.

**Comment by geerlingguy** [comment]
@mlcooper - I haven't run into this issue before, but I'm 99% sure it would be related to something in your local ssh config (`~/.ssh/config`) or something like `ssh-agent` that's making authentication fail.

Also, note that I think Packer is up to a 1.0 release, and VirtualBox up to 5.1.24 or so; newer versions might also fix those issues.
