### ISSUE TITLE
Packer can't find ansible roles

### ISSUE THREAD

**Issue by legleux** [geerlingguy/packer-centos-6#8]
I'm one of the unluckies trying this on windows.
Your instructions state: `you can simply clone the required Ansible roles from GitHub directly (use Ansible Galaxy to get the GitHub repository URLs for each role listed in requirements.txt), and update the role_paths variable to match the location of the cloned role.`

I took this to mean clone your two repos `ansible-role-packer-rhel` and `ansible-role-nfs` somewhere on the host machine, then change the `ansible/main.yml` file to point to the root of those clones.

Of course I wouldn't be here if that worked, so what am I doing wrong (besides trying this on windows?)

**Comment by geerlingguy** [comment]
You will also need to convert the role directory names manually—e.g. `mv ansible-role-packer-rhel geerlingguy.packer-rhel` (repeat for each role as required). This is because Ansible tries to use the roles as they're named by directory.
